version: '2'

services:
  database:
    image: mongo:3.6.8
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./database:/database

  app:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    # command: /sbin/my_init -- bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
     - "${PORT}:8080"
    volumes:
     - .:${API_DIR}

    links:
      - database
    environment:
      SERVICE: app
      APP_DIR: ${API_DIR}